BST and Basics Updates
sirhopsalot/lazarus_mq2_e3 pull request #29
Opened 2020-12-01 17:20 UTC by Cometnest

Added ability to check if Paragon and Auto Paragon is active on Beastlords. I also added a function in e3_Basics that allows you to send out instance invites. This mean no more manually typing out everyones names in groups and raids!

2020-12-01 18:18 UTC, sirhopsalot requested changes

2020-12-01 18:18 UTC, sirhopsalot commented on Macros/e3 Includes/e3_Basics.inc
> +#event sendInstanceInvites "<#1#> send instance invites"
How about "/bc inst invite" so it matches what you put in the chat box? 

Can just add a second event line:
#event sendInstanceInvites "<#1#> inst invite"

2020-12-01 18:18 UTC, sirhopsalot commented on Macros/e3 Includes/e3_Basics.inc
> +			/say #inst invite ${Raid.Member[${i}]}
You've tested this with a lot of raid members? It doesn't get rate limited?

2020-12-01 18:18 UTC, sirhopsalot commented on Macros/e3 Includes/e3_Basics.inc
> +			/say #inst invite ${Raid.Member[${i}]}
If necessary, you could build up a long string of names, then emit the #inst invite ${longStringOfNames}

2020-12-03 04:21 UTC, Cometnest commented
All issues should be resolved. Tested again tonight myself and all seems well. If you see anything else, let me know.

2020-12-03 15:13 UTC, sirhopsalot approved these changes

2020-12-03 15:14 UTC, merged